const inputBill = document.getElementById("bill")
const five = document.getElementById("five")
const ten = document.getElementById("ten")
const fifteen = document.getElementById("fifteen")
const twentyFive = document.getElementById("wentyFive")
const fifty = document.getElementById("fifty")
const custom = document.getElementById("custom")
const persons = document.getElementById("persons")
console.log("inputbBill", "five", "ten", "fifteen", "twentyFive", "fifty", "custom", "persons")